### ISSUE TITLE
我尝试修改你的插件，把它变成复制html也自动上传图片，但是没有效果

### ISSUE THREAD

**Issue by zhyit** [hanghang2/tinymce-pastewordimage#1]
我在源代码中加了判断http链接的方法
![@ 3@JQS8JOF OJ)PM~ C FE](https://github.com/hanghang2/tinymce-pastewordimage/assets/43231863/58acda71-ee32-4f50-9bf3-0d81cc56e1cd)
我已经同步获取并设置对应node的src的base64，但是没有调用相应的文件上传方法，并且我测试过直接把相应的图片文件的base64设置到node中是可以执行图片上传方法的

![TAK4%NTRS(K4DM{%)$@V1`A](https://github.com/hanghang2/tinymce-pastewordimage/assets/43231863/3fa7254b-2612-4534-b566-dc3b55503c2d)

![_1R714@%ITOV272~(`W3H)2](https://github.com/hanghang2/tinymce-pastewordimage/assets/43231863/175b6ba3-0b1f-4f97-aac4-24256583090a)

**Comment by hanghang2** [comment]
你意思是上传图片后去修改node的src，没有触发API中的images_upload_handler方法吗？

你在tinymce.js源码中看一看，应该是要触发SetContent才会去调用images_upload_handler方法吧，如下图：

![image](https://github.com/hanghang2/tinymce-pastewordimage/assets/25996792/06903668-369b-4631-8c50-a16bfd564a38)

![image](https://github.com/hanghang2/tinymce-pastewordimage/assets/25996792/5634f620-5c69-4821-83c2-663052b8b4cf)

![image](https://github.com/hanghang2/tinymce-pastewordimage/assets/25996792/2894d16d-715f-4ba3-b2f9-f40048fc7ed4)

![image](https://github.com/hanghang2/tinymce-pastewordimage/assets/25996792/87ae5757-8eeb-4be5-9243-df778ce25a2e)

**Comment by hanghang2** [comment]
如果是复制html内容，你可以尝试使用dom操作，例如innerHTML，把你粘贴的内容html文本内容放在里面。

**Comment by zhyit** [comment]
谢谢你的建议，我已解决这个问题，忘记关闭这个提问了，对不起，原因是plugin.min.js不支持async，await，所以只能先停止tinymce(e.preventDefault();)，具体实现的代码可以看看这个哦-忘了/tinymce6-paste - 码云 - 开源中国 (gitee.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月3日(星期三) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hanghang2/tinymce-pastewordimage] 我尝试修改你的插件，把它变成复制html也自动上传图片，但是没有效果 (Issue #1)





 
如果是复制html内容，你可以尝试使用dom操作，例如innerHTML，把你粘贴的内容html文本内容放在里面。
 
&mdash;
